### ISSUE TITLE
icao folder disappeared

### ISSUE THREAD

**Issue by mykola-bihun** [epranka/airports-db#3]
Hi,
The icao file (which is integral to the database) isn't in the repository anymore. This leads to 404 errors whenever trying to use it.
Could this please be fixed?

Thanks
Daniel

**Comment by mykola-bihun** [comment]
@epranka Bump

**Comment by epranka** [comment]
Hi, I will try to look, sorry

**Comment by epranka** [comment]
Built it locally. Don't know why it disappeared from Github (maybe some limitations). I have a plan to create a separate API service for it

**Comment by mykola-bihun** [comment]
Sounds great, no problem. Let me know when the external service is online. Thank you!
