### ISSUE TITLE
No ILS?

### ISSUE THREAD

**Issue by TenPatrol** [epranka/airports-db#4]
Smth is wrong with ILS in many airports for example CYVO
https://runway.airportdb.io/airport/CYVO
RWY 18 "ILS: No"
There is ILS

**Comment by TenPatrol** [comment]
Smth is wrong with ILS in many airports for example CYVO
https://runway.airportdb.io/airport/CYVO
RWY 18 "ILS: No"
There is ILS

**Comment by epranka** [comment]
Hello, something wrong with the automatic database update. Sorry

Fixed manually.
